name: Build SNAKE

on:
  push:
    branches: [master]
    paths:
      - "src/snake/**"
  pull_request:
    branches: [master]
    paths:
      - "src/snake/**"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src/snake

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
